name: Run Selenium Script Daily

# Schedule to run at 3:30 PM Kuala Lumpur time (7:30 AM UTC)
on:
  schedule:
    - cron: "30 7 * * *"
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the Selenium script
        env:
          WEBSITE_USERNAME: ${{ secrets.WEBSITE_USERNAME }}
          WEBSITE_PASSWORD: ${{ secrets.WEBSITE_PASSWORD }}
        run: |
          python main.py

      # Ensure the downloads directory exists and create a dummy file if empty
      - name: Ensure downloads directory exists
        run: mkdir -p downloads

      - name: Create dummy file if downloads is empty
        run: |
          if [ -z "$(ls -A downloads)" ]; then
            echo "No downloads available" > downloads/dummy.txt
          fi

      - name: Upload Downloaded Files
        uses: actions/upload-artifact@v2
        with:
          name: downloaded-files
          path: downloads/
          if-no-files-found: warn
